config/routes.rb
Familyfeast::Application.routes.draw do
  match "/browseresdeals" => "home#browseresdeals"
  match "/browseresitems" => "home#browseresitems"
  match "/browserestaurants" => "home#browserestaurants"
  match "/salesstats" => "deals#salestats"
  get "home/buy"
  get "home/test"
  root :to => "home#index"
  devise_for :users
  devise_for :users do get '/user_signout' => 'devise/sessions#destroy' end
  resources :menuitems
  devise_for :owners
  devise_for :owners do get '/owner_signout' => 'devise/sessions#destroy' end
  resources :deals
  post "deals/create" => "deals#create"
  match  "newdeal/launch/:id" => "deals#launch"
  match "newdeal/launched"=> "deals#launched" , :via => :post
  match "/userdeals" => "home#userdeals"
  match "/order" => "home#order"
  match "/mid_edit" => "deals#mid_edit"
  match "/showdeals" => "home#showdeals"
  match "/restaurants" => "home#restaurants"

 
end

app/models/menuitem.rb
class Menuitem
  include Mongoid::Document
  field :name, type: String
  field :size, type: String
  field :price, type: String
  belongs_to :owner
end

app/controllers/menuitems_controller.rb
class MenuitemsController < ApplicationController
  # GET /menuitems
  # GET /menuitems.json
   before_filter :authenticate_owner!



  def index
    @owner= current_owner
    @menuitems = @owner.menuitems.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menuitems }
    end
  end

  # GET /menuitems/1
  # GET /menuitems/1.json
  def show
    @menuitem = Menuitem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menuitem }
    end
  end

  # GET /menuitems/new
  # GET /menuitems/new.json
  def new
    @owner = current_owner
    @menuitem = @owner.menuitems.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menuitem }
    end
  end

  # GET /menuitems/1/edit
  def edit
    @menuitem = Menuitem.find(params[:id])
  end

  # POST /menuitems
  # POST /menuitems.json
  def create
    @owner=current_owner
    @menuitem =@owner.menuitems.new(params[:menuitem])

    respond_to do |format|
      if @menuitem.save
        format.html { redirect_to @menuitem, notice: 'Menuitem was successfully created.' }
        format.json { render json: @menuitem, status: :created, location: @menuitem }
      else
        format.html { render action: "new" }
        format.json { render json: @menuitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menuitems/1
  # PUT /menuitems/1.json
  def update
    @menuitem = Menuitem.find(params[:id])

    respond_to do |format|
      if @menuitem.update_attributes(params[:menuitem])
        format.html { redirect_to @menuitem, notice: 'Menuitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menuitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menuitems/1
  # DELETE /menuitems/1.json
  def destroy
    @menuitem = Menuitem.find(params[:id])
    @menuitem.destroy

    respond_to do |format|
      format.html { redirect_to menuitems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/menuitems_helper.rb
module MenuitemsHelper
end

app/views/menuitems/_form.html.erb
<%= form_for(@menuitem) do |f| %>
  <% if @menuitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menuitem.errors.count, "error") %> prohibited this menuitem from being saved:</h2>

      <ul>
      <% @menuitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menuitems/edit.html.erb
<h1>Editing menuitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @menuitem %> |
<%= link_to 'Back', menuitems_path %>

app/views/menuitems/index.html.erb
<h1>Listing menuitems</h1>

                   <div class= "row-fluid" style="border: 1px solid black; border-radius: 10px;">


<table>
  <tr>
    <th>Name</th>
    <th>Size</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menuitems.each do |menuitem| %>
  <tr>
    <td><%= menuitem.name %></td> 
    <td><%= menuitem.size %></td>
    <td><%= menuitem.price %></td> <td>
    <td><%= link_to 'Edit', edit_menuitem_path(menuitem) %></td>
    <td><%= link_to 'Destroy', menuitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menuitem', new_menuitem_path %>





                   </div>

app/views/menuitems/new.html.erb
<h1>New menuitem</h1>

<%= render 'form' %>

<%= link_to 'Back', menuitems_path %>

app/views/menuitems/show.html.erb
<p id="notice"><%= notice %></p>

   <table>
  <tbody>
  <tr>
  <th>Name </th>

  <th>Size </th>

  <th>Price </th>
</tr>
  <tr>
   
   
    <td> <%= @menuitem.name %></td>

    <td><%= @menuitem.size %></td>
    <td><%= @menuitem.price %></td>
  </tr>
  </tbody>
</table>
<%= link_to 'Edit', edit_menuitem_path(@menuitem) %> |
<%= link_to 'Back', menuitems_path %>