config/routes.rb
Familyfeast::Application.routes.draw do
  match "/browseresdeals" => "home#browseresdeals"
  match "/browseresitems" => "home#browseresitems"
  match "/browserestaurants" => "home#browserestaurants"
  match "/salesstats" => "deals#salestats"
  get "home/buy"
  get "home/test"
  root :to => "home#index"
  devise_for :users
  devise_for :users do get '/user_signout' => 'devise/sessions#destroy' end
  resources :menuitems
  devise_for :owners
  devise_for :owners do get '/owner_signout' => 'devise/sessions#destroy' end
  resources :deals
  post "deals/create" => "deals#create"
  match  "newdeal/launch/:id" => "deals#launch"
  match "newdeal/launched"=> "deals#launched" , :via => :post
  match "/userdeals" => "home#userdeals"
  match "/order" => "home#order"
  match "/mid_edit" => "deals#mid_edit"
  match "/showdeals" => "home#showdeals"
  match "/restaurants" => "home#restaurants"

 
end

app/models/deal.rb
class Deal
  include Mongoid::Document
  include Mongoid::Timestamps
  field :type, type: String
  field :postcode, type: String
  field :price, type: String
  field :location, type: String
  field :launched, type: Integer
  field :name, type: String
  field :restaurant_name, type: String
  field :home, type: Integer
  field :pick, type: Integer
  field :table, type: Integer
  field :month, type: Integer
  
  MONTHS = [1,2,3,4,5,6,7,8,9,10,11,12]
  after_create:add_month


  protected
  def add_month
    self.update_attributes(:month => Deal::MONTHS.sample)
  end
  
  
  
  
  
  
  
  
  
  
  
  
  belongs_to :owner
  belongs_to :user
  embeds_many :menuitems
  has_many :sales
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # GET /deals
  # GET /deals.json
 before_filter :authenticate_owner!
  def index
    @owner= current_owner
    @deals = @owner.deals.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
    @deal = Deal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.json
  def new
    @owner=current_owner
    @menuitems = @owner.menuitems.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @owner= current_owner
    @menuitems= @owner.menuitems.all
    @deal = Deal.find(params[:id])
   if params[:mid]
     @deal.menuitems.where(:id=>params[:mid]).delete

   respond_to do |format|
   format.html {}
    end
   end

  end
  # PUT /deals/1
  # PUT /deals/1.json
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

      format.json { head :no_content }
  end


  def mid_edit
    if params[:createdeal]

         @deal= Deal.find(params[:did])
         @dealmenu = @deal.menuitems

          params[:createdeal].each do |id|

              @dealmenu << Menuitem.find(id)

           end

         @deal.update_attributes(:price => params[:price], :menuitems => @dealmenu)
    end

    respond_to do |format|
      format.html { }
     end

  end



  def create
   @owner= current_owner
   if params[:options]
    params[:options].each do |opt|
      if opt == "table"
        @table=1
      end
      if opt == "pick"
        @opt=1
      end
      if opt == "home"
        @home=1
      end
    end
   end
   @dealnew= @owner.deals.new(:restaurant_name=>@owner.restaurant_name, :home=>@home, :pick=>@pick, :table=>@table, :location=>@owner.location , :type=> @owner.type, :postcode=> @owner.postcode, :price=>params[:price], :name=>params[:name])
     @dealitems= @dealnew.menuitems
     params["createdeal"].each do |id|
      @dealitems <<  Menuitem.find(id)
     end

     id = @dealnew.id
     @dealnew.save
     session[:newdeal]= @dealnew._id
     respond_to do |format|
      format.html {render json: {'id'=>id} }
     end

  end

  def launch
   respond_to do |format|
     format.html { }
   end
  end

  def launched
   @id= params[:launch].keys[0]
   @deal= Deal.find(@id) 
   @deal.update_attributes(:launched => 1)
  end

  def salestats
    @owner= current_owner
    @dealowner= @owner.deals.all
  end










end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<script type="text/javascript">
    document.write("\<script src='http://code.jquery.com/jquery-latest.min.js' type='text/javascript'>\<\/script>");
</script>



<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved: </h2>

       <ul>
        <% @deal.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
        <% end %>
       </ul>
     </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br />
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div >
   <% @deal.menuitems.each do |menuitem| %>
     <% did=@deal.id %>
     <button type="button" id="<%= did.to_s + "_" + menuitem.id.to_s %>" onclick="postid(this.id);" class="btn-primary">  Delete <%= menuitem.name %> <br>
   <% end %>
  </div>
  <div class="span7">
   <table>
    <% @menuitems.each do |menuitem| %>

     <tr>
       <td><%= menuitem.name %></td> 
       <td><%= menuitem.size %></td>
       <td><%= menuitem.price %></td> <td>
         <% menuitemall = menuitem.name + "_" + menuitem.size + "_" + menuitem.price + "_" + menuitem.id %>
         <label class="checkbox">
         <input type="checkbox" id=<%=menuitemall%> onclick="deal(this.id);" >
     </tr>
    <% end %>
   </table>
  </div>



       <div class="span4">


                   <div class="row-fluid" id="rp">
                   </div>
                   <div class="row-fluid">
                       <input id="price1" type="text" placeholder="Set Price"> <br>
                  </div>

                  <div class="row-fluid">
                     <br>  <button type="button" id='<%= @deal.id %>' onclick="postarray(this.id);" class="btn-primary">Configure Deal</button>
                 </div>
      </div>




<% end %>

<script>
 var createdeal=[];
 var sum=[];
 var total=0;

 function postid(mid){
   console.log(window.location.origin);
   dealid= mid.split("_")[0]
   miid= mid.split("_")[1]
   console.log(dealid);
   $.ajax({
     type:"GET",
     data:{ mid: miid },
     url:   window.location.orgin ,
     success: function(){alert: "asdf", window.location= window.location.origin + "/deals/" + dealid + "/edit"; }
     });
 }

   function remove(id)
    {
        return (elem=document.getElementById(id)).parentNode.removeChild(elem);
    }





    function deal(mi){
      var name = mi.split("_")[0];
      var size = mi.split("_")[1];
      var price= mi.split("_")[2];
      var id = mi.split("_")[3];
      var elem = $("#"+name+size+price);

       if (elem.text() == "")
         {
           $('#mis').append("<div id='"+name+size+price+"'>"+ name + " " + price  +"</div>");
           createdeal.push(id);
           sum.push(price)
           console.log(createdeal);
           dp= document.getElementById('deal_price').value;

           total=  (eval(sum.join('+')));
           dp= document.getElementById('deal_price').value;
           dp=parseFloat(dp);
           total= total + dp;
           console.log(total);
           document.getElementById('rp').innerHTML="<br><br><p>Retail Price  " + total + " $</p>";
        }


      else
        {
          remove(name+size+price);
          var indx = createdeal.indexOf(id);
          var indx1= sum.indexOf(price)
          createdeal.splice(indx,1);
          sum.splice(indx1,1);
          total=  (eval(sum.join('+')));
          dp= document.getElementById('deal_price').value;
          dp=parseFloat(dp);
          total= total + dp;

          document.getElementById('rp').innerHTML="<br><br><p>Retail Price  " + total + " $</p>";
          console.log(createdeal);}
        }

      function postarray(dealid)
        {
           var price= $('#price1').val();
          console.log(price);
          $.ajax({type: "get",
            data:{createdeal: createdeal, did: dealid, price: price},
            url: window.location.origin + "/mid_edit"   ,
            success: function(){ window.location= window.location.origin + "/deals/" + dealid + "/edit" ; }
          });
        }



</script>

app/views/deals/customer.html.erb
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQfDC9PzdmI4M2QIN7wjSZzKiwbCyjqdI&sensor=false"></script>
<script src="http://code.jquery.com/jquery-latest.min.js"> </script>


<h1>What would you like today? </h1>
   <%= form_tag '/', :method => 'get' do %>
     <br>
     I'd like: <input placeholder="italian, thai, mexican etc" autocomplete="off" type="text" name="type" data-provide="typeahead" data-source='<%= Deal.all.collect(&:type).uniq! %>'>    in: <input placeholder="Your Postcode" autocomplete="off" type="text" name="postcode" data-provide="typeahead" data-source='<%= Deal.all.collect(&:postcode).uniq! %>'>
     <%= submit_tag "Filter deals" %>
  <% end %>


  <% @filter.each do |available| %>

    <ul class="nav nav-tabs" id="mytab">
      <li class="active"><a data-toggle="tabs" href="#deal" >Deal Details</a></li>
      <li><a data-toggle="tabs" href="#about" >About</a></li>
      <li><a data-toggle="tabs" href="#location" >Location</a></li>
      <li><a data-toggle="tabs" href="#other" >Other</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="deal">
          <div class= "row-fluid">
            <div class= "span8" style="border: 1px solid black; border-radius: 10px;">
              <h4>
                  By : <%= available.owner.res_name%><br>
                     <% available.menuitems.size.times do |ms| %>
                     <%= available.menuitems[ms].name%><br>
                     <%= available.menuitems[ms].price%><br>
                <% end %>
              </h4>
            </div>
            <div class= "span4" style="border: 1px solid black; border-radius: 10px;">
                <h4> <%= available.price %></h4>
                  <%= form_tag 'userdeals', :method=> 'get' do %>
                    <%= submit_tag "getdeal", :name=>"get[#{available.id}]" %>
                  <% end %>
            </div>
          </div>
       </div>
       <div class="tab-pane" id="about"></div>
       <div class="tab-pane" id="location"> asdf </div>
       <div class="tab-pane" id="other"></div>
     </div>

         <% end %>
                <script>
               $(function () {
                 $('#mytab a[href="#deal"]').tab('show');
                 $('#mytab a[href="#about"]').tab('show');
                 $('#mytab a[href="#location"]').tab('show');
                 $('#mytab a[href="#other"]').tab('show');
               })





                </script>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<table class="table table-striped table-hover table-bordered">
  <tr>
    <th>Type</th>
    <th>Postcode</th>
    <th>Price</th>
    <th>Location</th>
    <th>Menu Items</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @ldeals=@deals.where(:launched=> 1) %>

  <h3>
    Unlaunched Deals
  </h3>

<% @ldeals.each do |deal| %>
  <tr>
    <td><%= deal.type %></td>
    <td><%= deal.postcode %></td>
    <td><%= deal.price %></td>
    <td><%= deal.location %></td>
    <td> <% deal.menuitems.each do |menuitem| %>
           <%= menuitem.name  %>   <%= menuitem.size %>
       <br> <% end %></td>


    <td><%= link_to 'Show', deal %></td>
    <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
    <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<table class="table table-striped table-hover table-bordered">
  <tr>
    <th>Type</th>
    <th>Postcode</th>
    <th>Price</th>
    <th>Location</th>
    <th>Menu Items</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @uldeals=@deals.where(:launched=> nil) %>
  <h3>
    Unlaunched Deals 
  </h3>
<% @uldeals.each do |deal| %>
  <tr>
    <td><%= deal.type %></td>
    <td><%= deal.postcode %></td>
    <td><%= deal.price %></td>
    <td><%= deal.location %></td>
    <td> <% deal.menuitems.each do |menuitem| %><br>
   <%= menuitem.name  %>   <%= menuitem.size %>
 <% end %></td>

    <td><%= link_to 'Show', deal %></td>
    <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
    <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td> <%= form_tag '/newdeal/launched', :method=>'post' do %>
        <%= submit_tag 'launch', :name => "launch[#{deal.id}]" %>
      <% end %>

  </tr>
<% end %>
</table>

<%= button_to "New Deal", new_deal_path, :class=> "btn btn-primary btn-large", :method => :get  %>
<%= link_to 'New Deal', new_deal_path %>

app/views/deals/launch.html.erb
<h1> DEAL </h1>

<button type="button" onclick="launchdeal();" class="btn-primary">Launch Deal </button>







<script>
function launchdeal()
{ $.ajax({type:"POST",
          url: window.location.origin + "/newdeal/launched",
          success: function(){alert("Deal was successfully launched!");}
         })
}
</script>

app/views/deals/launched.html.erb
<h1> Deal Launched </h1>

app/views/deals/new.html.erb
<h1>New deal</h1>

          <div class= "row-fluid">
               <div class= "span8" style="border: 1px solid black; border-radius: 10px;">


                  <table class="table table-bordered table-hover">
                       <tr>
                        <th>Name</th>
                        <th>Size</th>
                        <th>Price</th>
                       </tr>

                    <% @menuitems.each do |menuitem| %>
                      <tr>
                        <td><%= menuitem.name %></td> 
                        <td><%= menuitem.size %></td>
                        <td><%= menuitem.price %></td> <td>
                          <% menuitemall = menuitem.name + "_" + menuitem.size + "_" + menuitem.price + "_" + menuitem.id %>
                         <label class="checkbox">
                         <input type="checkbox" id=<%=menuitemall%> onclick="deal(this.id);" >
                      </tr>
                    <% end %>
                  </table>

<br />

                    <%= button_to 'New Menuitem', new_menuitem_path, :method => :get, :class => "btn btn-primary" %>





              </div>

              <div class="span3">
                   <div class="row-fluid">
                     <input id="dname" type="text" placeholder="Name"><br>
                     Table booking <input id="table" type="checkbox" onclick="options(this.id);"><br>
                     Home delivery <input id="home" type="checkbox" onclick="options(this.id);"><br>
                     Take away <input id="pick" type="checkbox" onclick="options(this.id);">
                  </div>

                   <div class="row_fluid" id="mis">Deal Preview<br>

                     <br>
                     Name Price <br>


                  </div>
                  <div class="row-fluid" id="rp">
                  </div>
                  <div class="row-fluid">
                    <input id="price" type="text" placeholder="Set Price"> <br>
                  </div>
                  <div class="row-fluid">
                     <br>  <button type="button" onclick="postarray();" class="btn-primary">Configure Deal</button>
                  </div>
             </div>

  <script>
   var createdeal=[];
   var sum=[];
   var total=0;
   var opt=[]
        function remove(id)
    {
        return (elem=document.getElementById(id)).parentNode.removeChild(elem);
    }

    function options(di){
        opt.push(di)
    }

     function deal(mi){
      var name = mi.split("_")[0];
      var size = mi.split("_")[1];
      var price= mi.split("_")[2];
      var id = mi.split("_")[3];
      var elem = $("#"+name+size+price);

      if (elem.text() == "")
        {
          $('#mis').append("<div id='"+name+size+price+"'>"+ name + " " + price  +"</div>");
          createdeal.push(id);
          sum.push(price)
          console.log(createdeal);
          total=  (eval(sum.join('+')));
          document.getElementById('rp').innerHTML="<br><br><p>Retail Price  " + total + " $</p>";
        }


      else
        {
          remove(name+size+price);
          var indx = createdeal.indexOf(id);
          var indx1= sum.indexOf(price)
          createdeal.splice(indx,1);
          sum.splice(indx1,1);
           total=  (eval(sum.join('+')));
           document.getElementById('rp').innerHTML="<br><br><p>Retail Price  " + total + " $</p>";
          }
        }

      function postarray()
        {  var name = $('#dname').val();
           var price= $('#price').val();
          $.ajax({type: "POST",
            beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
            data:{createdeal: createdeal, options: opt, name: name , price: price},
            url: window.location.origin + "/deals/create.html",
            success: function(response){ window.location.href = $.parseJSON(response)["id"];  }
          });
        }
  </script>

app/views/deals/salestats.html.erb
 <script type="text/javascript" src="https://www.google.com/jsapi"></script>
 <script type="text/javascript">
     google.load("visualization", "1", {packages:["corechart"]});
     google.setOnLoadCallback(drawChart);
     function drawChart() {
         var data = google.visualization.arrayToDataTable([
           ['Month', 'Deals Launched'],
           ['January', <%=@dealowner.where(:month=> 1).size%>],
           ['Feburary',<%=@dealowner.where(:month=> 2).size%>],
           ['March', <%=@dealowner.where(:month=> 3).size%>],
           ['April', <%=@dealowner.where(:month=> 4).size%>]
         ]);

          var options = {
          title: 'Deal Performance'
          };

         var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
         chart.draw(data, options);
     }
     
     google.setOnLoadCallback(drawCharts);
     function drawCharts() {
     <% @owner.deals.each do |deal| %>
         var data1 = google.visualization.arrayToDataTable([
           ['Month', 'Deals Sold'],
           ['January', <%=deal.sales.where(:month=> 1).size%>],
           ['Feburary',<%=deal.sales.where(:month=> 2).size%>],
           ['March', <%=deal.sales.where(:month=> 3).size%>],
           ['April', <%=deal.sales.where(:month=> 4).size%>]
         ]);

          var options1 = {
          title: 'Deal Sale'
          };

         var chart = new google.visualization.LineChart(document.getElementById('<%= deal.id %>'));
                               chart.draw(data1, options1);
 
   <% end %>
     }
</script>

    <div id="chart_div" style="width: 700px; height: 300px;"></div>

<% @owner.deals.each do |deal|%>
   <h4>Deal details </h4>
   Deal name:<%= deal.name %><br>
   Deal price:<%= deal.price  %><br>
   Menu-items:
   <% deal.menuitems.each do |item| %>
      <%= item.name %>
    <% end %>

   <h4> Sale details </h4>
   <div id='<%=deal.id%>' style="width: 900px; height: 200px;"></div>
  
  
  
   Total sales: <%=deal.sales.size %><br>
    Sales ids <br>
    <table class="table table-bordered table-hover">
        <td>
       User name
        </td>
        <td>
        Confirmation Code
        </td>
    <% deal.sales.each do |sale| %>
      <tr>
        <td>
          <% @user= User.find(sale.uid) %>
          <%= @user.name%>
      </td>
      <td>
        <%= sale.confirmation_code %><br>
    </td>
      </tr>
   <% end %>
    </table>
<% end %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>



<p>
<b>Menu Items:</b><br>
     Name                          Size                         Price  <br>
 
  <% @deal.menuitems.each do |menuitem| %><br>
   <%= menuitem.name  %>     <%= menuitem.size %>         <%= menuitem.price %> 
  <% end %>
 
 
 
 
</p>


<p>
  <b>Type:</b>
  <%= @deal.type %>
</p>


<p>
  <b>Location:</b>
  <%= @deal.location %>
</p>


<p>
  <b>Postcode:</b>
  <%= @deal.postcode %>
</p>

<p>
  <b>Price:</b>
  <%= @deal.price %>
</p>


<%= button_to 'Edit', edit_deal_path(@deal), :method => :get , :class => "btn btn-primary"%> 
<%= button_to 'Back', deals_path, :method => :get, :class => "btn btn-primary"%>

app/views/deals/userdeals.html.erb
<h2> Great Choice </h2>
<% @dealorder.menuitems.each do |items| %>
  <%= items.name %>   <%= items.size %>   <%= items.price %><br>
<% end %>
<br />
<br />
<br />
<% if user_signed_in? %>
  Welcome back to dealchef! <%= current_user.email %>
  Here's the list of deals you already have:
<% Deal.where(:user_id => current_user.id).each do |deal| %>
  <br />
  <br />
  Deal :
  <% deal.menuitems.each do |item| %>
    <%= item.name %> <%= item.size %> <%= item.price %>
  <% end %>
<% end %>
<% else %>
  <br />
  <br />
  Already a Registered User, Sign in Here!
<%= link_to "SignIn Here", "/users/sign_in" %>
  <br />
  <br />
  Register your account on DealChef!
<%= link_to "SignUp Here", "/users/sign_up" %>
<% end %>