config/routes.rb
Familyfeast::Application.routes.draw do
  match "/browseresdeals" => "home#browseresdeals"
  match "/browseresitems" => "home#browseresitems"
  match "/browserestaurants" => "home#browserestaurants"
  match "/salesstats" => "deals#salestats"
  get "home/buy"
  get "home/test"
  root :to => "home#index"
  devise_for :users
  devise_for :users do get '/user_signout' => 'devise/sessions#destroy' end
  resources :menuitems
  devise_for :owners
  devise_for :owners do get '/owner_signout' => 'devise/sessions#destroy' end
  resources :deals
  post "deals/create" => "deals#create"
  match  "newdeal/launch/:id" => "deals#launch"
  match "newdeal/launched"=> "deals#launched" , :via => :post
  match "/userdeals" => "home#userdeals"
  match "/order" => "home#order"
  match "/mid_edit" => "deals#mid_edit"
  match "/showdeals" => "home#showdeals"
  match "/restaurants" => "home#restaurants"

 
end

app/views/layouts/_navigation.html.erb
<%= link_to "Family Feast", root_path, :class => 'brand' %>
<ul class="nav">
    <% if owner_signed_in? %>
        <li>
          <%= link_to 'Owner Logout', "/owner_signout" , :method=>'delete' %>
        </li>
        <li>
          <%= link_to 'Edit account', edit_owner_registration_path %>
        </li>
    <% end %>

    <% if user_signed_in? %>
        <li>
        <%= link_to 'User Logout', "/user_signout" , :method=>'delete' %>
        </li>
    <% end %>

    <% if !user_signed_in? %>
      <li>
        <%= link_to 'User Login', new_user_session_path %>
      </li>
      <li>
        <%= link_to 'User SignUp', new_user_registration_path %>
      </li>
    <% end %>

    <% if !owner_signed_in? %>
      <li>
        <%= link_to 'Owner Login', new_owner_session_path %>
      </li>
      <li>
        <%= link_to 'Owner SignUp', new_owner_registration_path %>
      </li>
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Familyfeast" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
      <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
      <script src="assets/bootstrap.js" type="text/javascript"></script>
      <script src="assets/prettify.js" type="text/javascript"></script>
      <script src="assets/lightbox.js" type="text/javascript"></script>
      <script src="assets/main.js" type="text/javascript"></script>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->

    </head>
  <body>
    <div class='navbar navbar-fixed-top navbar-inverse'>
                <div class='navbar-inner'>
                  <div class='container'>
                    <a class='btn btn-navbar' data-target='.nav-collapse' data-toggle='collapse'>
                      <span class='icon-bar'></span>
                      <span class='icon-bar'></span>
                      <span class='icon-bar'></span>
                    </a>
                    <a href="#" class="brand">Save on Meals</a>
                    <div class='nav-collapse subnav-collapse collapse pull-right' id='top-navigation'>
                      <ul class='nav'>
                        <li class='active'>
                          <a href="/">Home</a>
                        </li>
                         <li class=''>
                          <a href="restaurants.html">Restaurants</a>
                        </li span12>
                        <li class='dropdown'>
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Features</a>
                          <ul class='dropdown-menu'>
                            <li>
                              <a href="#">Pricing Table</a>
                            </li>
                            <li>
                              <a href="#">Awesome Icons</a>
                            </li>
                            <li>
                              <a href="#">Basic Elements</a>
                            </li>
                            <li class='divider'></li>
                            <li class='nav-header'>Pages Examples</li>
                            <li>
                              <a href="#">About Us Page</a>
                            </li>
                            <li>
                              <a href="#">Gallery of Images</a>
                            </li>
                            <li>
                              <a href="#">Page not found</a>
                            </li>
                            <li>
                              <a href="#">Coming Soon Page</a>
                            </li>
                          </ul>
                        </li>
                        <li class='dropdown'>
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Doc</a>
                          <ul class='dropdown-menu'>
                            <li>
                              <a href="#">Get Started</a>
                            </li>
                            <li>
                              <a href="#">Scaffolding</a>
                            </li>
                            <li>
                              <a href="#">Base CSS</a>
                            </li>
                            <li>
                              <a href="#">Components</a>
                            </li>
                            <li>
                              <a href="#">Javascript</a>
                            </li>
                          </ul>
                        </li>
                        <li class='dropdown'>
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog</a>
                          <ul class='dropdown-menu'>
                            <li>
                              <a href="#">Single Post</a>
                            </li>
                            <li>
                              <a href="#">Multiple Posts (two)</a>
                            </li>
                            <li>
                              <a href="#">Multiple Posts (one)</a>
                            </li>
                          </ul>
                        </li>
                        <li class=''>
                          <a href="#">Contact</a>
                        </li>
                      </ul> 

                      <div class='top-account-control visible-desktop'>
                          <% if user_signed_in? %> 
                                <li>
                                   <%= link_to 'User Logout', "/user_signout"  %> 
                                </li>
                          <% end %>
                          <% if owner_signed_in? %> 
                               <li>
                                   <%= link_to 'Restaurant Logout', "/owner_signout"  %></li> 
                               <li>  <%= link_to 'My Deals', '/deals' %>   <%= link_to 'My Menuitems', '/menuitems' %>
                               </li>
                          <% end %>

                          <% if !user_signed_in? && !owner_signed_in?%>
                             <a href="users/sign_up" class="top-create-account">Create Account</a>
                             <a href='#' class="top-sign-in">Sign In</a>
                             <div class='login-box'>
                                <a class='close login-box-close' href='#'>&times;</a>
                                <div class="row-fluid">
                                   <div class="span5">

                                      <h4 class='login-box-head'>Customer Login</h4>
                                      <div class='control-group'> 
                                        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
                                            <div><%= f.label :email %>
                                            <%= f.email_field :email, :autofocus => true %></div>

                                            <div><%= f.label :password %>
                                            <%= f.password_field :password %></div>

                                           <% if devise_mapping.rememberable? -%>
                                              <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
                                            <% end -%>

                                           <div><%= f.submit "Sign in" %></div>
                                        <% end %>
                                     </div>
                                   <div class="span6">
                                    <h4 class='login-box-head'>Restaurant Login</h4> 
                                     <%= form_for(resource, :as => res_name, :url => session_path(res_name)) do |f| %>
                                        <div><%= f.label :email %>
                                        <%= f.email_field :email, :autofocus => true %></div>

                                        <div><%= f.label :password %>
                                        <%= f.password_field :password %></div>

                                        <% if devise_mapping.rememberable? -%>
                                          <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
                                         <% end -%>

                                        <div><%= f.submit "Sign in" %></div>
                                    <% end %>
                                  <% end %>
                                  </div>
                                </div>


                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="container-fluid">
                <div class="row-fluid">
                  <div class="span12">
                     <%= bootstrap_flash %>
                     <%= yield %>
                 </div>
                </div><!--/row-->

          <footer>

              <div class='pre-footer'>
                <div class='container-fluid'>
                  <div class='row-fluid'>
                    <div class='span4'>
                      <h5 class='footer-header'>Product</h5>
                      <ul class='footer-list'>
                        <li>
                          <a>Tour</a>
                        </li>
                        <li>
                          <a>Sign Up</a>
                        </li>
                        <li>
                          <a>Is it really free?</a>
                        </li>
                        <li>
                          <a>Are you a restaurant?</a>
                        </li>
                      </ul>
                    </div>
                    <div class='span4'>
                      <h5 class='footer-header'>Company</h5>
                      <ul class='footer-list'>
                        <li>
                          <a>About Save On Meals</a>
                        </li>
                        <li>
                          <a>Careers</a>
                        </li>
                        <li>
                          <a>Press & Media</a>
                        </li>
                        <li>
                          <a>Terms of Service</a>
                        </li>
                        <li>
                          <a>Privacy Policy</a>
                        </li>
                        <li>
                          <a>Contact Us</a>
                        </li>
                      </ul>
                    </div>
                    <div class='span4'>
                      <h5 class='footer-header'>Community</h5>
                      <ul class='footer-list'>
                      <li>
                          <a>Blog</a>
                        </li>
                        <li>
                          <a>Help Center</a>
                        </li>
                        <li>
                          <a>Twitter</a>
                        </li>
                        <li>
                          <a>Facebook</a>
                        </li>
                        <li>
                          <a>Google +</a>
                        </li>
                        <li>
                          <a>Contact Us</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div class='deep-footer'>
                <div class='container-fluid'>
                  <div class='row-fluid'>
                    <div class='span6'>
                      <div class='copyright'>Copyright &copy; 2013 Save On Meals Pty Ltd. All rights reserved.</div>
                    </div>
                    <div class='span6'>
                      <div class='copyright pull-right whitewash'><a href="#">Don't click here</a></div>
                    </div>
                  </div>
                </div>
              </div>
         </footer>

                    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>